from http.cookiejar import debug
from flask import Flask, request, jsonify
from openai import OpenAI
from dotenv import load_dotenv
import os
import json

# Load environment variables i.e. HF_TOKEN from .env file.
load_dotenv()

# Initialise OpenAI client using the Hugging Face router
client = OpenAI(
    base_url = "https://router.huggingface.co/v1",
    api_key = os.environ["HF_TOKEN"]
)

# Flask app instance
app = Flask(__name__)

@app.get("/generate_puzzles")
def generate_puzzles():
    topic = request.args.get("topic", "general")

    # Prompt sent to the model.
    prompt = f"""
    You must output ONLY valid JSON. Do NOT add explanations, text, comments, or code fences.
    
    Create 3 educational escape room puzzles about "{topic}".
    Each puzzle MUST use this exact field order:
    1.type
    2.question
    3.options
    4.answer
    5.hint
    Return ONLY a JSON array of 3 objects in exactly this type of format:
    [
        {{
            type: "...",
            question: "...",
            options: [... or null],
            answer: "...",
            hint: "..."
        }},
        ...
    ]

    Puzzles can have different types such as multiple choice questions, where there are options of answers to choose from or text questions
    Puzzles should be short and increase in difficulty from easy to hard.
    
    Do NOT change the field order.
    Do NOT add other fields.
    Do NOT include any text outside the JSON.
    Output ONLY valid JSON.
    """

    response = client.chat.completions.create(
        model = "moonshotai/Kimi-K2-Instruct-0905",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    # Extraction of text generated by model.
    ai_text = response.choices[0].message.content
    puzzles = json.loads(ai_text)

    print(ai_text);

    return jsonify({"topic": topic, "puzzles": puzzles})



if __name__ == "__main__":
    app.run(debug=True)